[package]
name = "libkarst"
version = "0.1.0"
authors = ["Vadim Chekan <kot.begemot@gmail.com>"]
edition = "2018"

[lib]
name = "karst"
crate-type = ["cdylib"]

[dependencies]
kafka4rust = {path = "../"}
tokio = "1.23"
lazy_static = "1.4"
anyhow = "1.0"

log = "0.4"
simple_logger = "1.6"