[package]
name = "libkarst"
version = "0.1.0"
authors = ["Vadim Chekan <kot.begemot@gmail.com>"]
edition = "2018"

[lib]
name = "karst"
crate-type = ["cdylib"]

[dependencies]
kafka4rust = {path = "../"}
tokio = "1"
lazy_static = "1"
anyhow = "1"

log = "0.4"
simple_logger = "4"