version: '3'
services:
  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"
  zkui:
    image: qnib/plain-zkui@sha256:d66972bd886ade9a8d7383f5064bd825f6d29275a282250cb0adf52475f67726
    ports:
      - "9090:9090"
    environment:
      - ZK_SERVER=zookeeper:2181
  broker1:
    image: kafka4rust-broker
    build:
      context: .
    depends_on:
      - zookeeper
    environment:
      BROKER_OPTS: >-
        --override advertised.listeners=PLAINTEXT://broker1:9092
        --override broker.id=1
        --override zookeeper.connect=zookeeper:2181
