version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - kafkanet
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  broker1:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - kafkanet
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
    - KAFKA_CFG_LISTENERS=INTERNAL://:9192,CLIENT://:9092
    - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://:9192,CLIENT://localhost:9092
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL

  broker2:
    image: bitnami/kafka:latest
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    networks:
      - kafkanet
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9192,CLIENT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://:9192,CLIENT://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL

  broker3:
    image: bitnami/kafka:latest
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper
    networks:
      - kafkanet
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT  # SASL_PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9192,CLIENT://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://:9192,CLIENT://localhost:9094
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
networks:
  kafkanet:
    