version: '3'
services:
  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"
    networks:
      - hostnet
  zkui:
    image: qnib/plain-zkui@sha256:d66972bd886ade9a8d7383f5064bd825f6d29275a282250cb0adf52475f67726
    ports:
      - "9090:9090"
    environment:
      - ZK_SERVER=zookeeper:2181
    networks:
      - hostnet
#  jaeger:
#    # UI http://localhost:16686
#    image: jaegertracing/all-in-one:1.17
#    environment:
#      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
#    ports:
#      - "5775:5775/udp"
#      - "6831:6831/udp"
#      - "6832:6832/udp"
#      - "5778:5778"
#      - "16686:16686"
#      - "14268:14268"
#      - "14250:14250"
#      - "9411:9411"
  broker1:
    image: kafka4rust-broker
    ports:
      - "9092:9092"
    build:
      context: .
    depends_on:
      - zookeeper
    networks:
      - hostnet
    environment:
      BROKER_OPTS: >-
        --override broker.id=1
        --override advertised.listeners=INSIDE://:9094,OUTSIDE://localhost:9092
        --override listeners=INSIDE://:9094,OUTSIDE://:9092
        --override listener.security.protocol.map=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        --override inter.broker.listener.name=INSIDE
        --override zookeeper.connect=zookeeper:2181
        --override num.partitions=10
  broker2:
    image: kafka4rust-broker
    ports:
      - "9093:9093"
    build:
      context: .
    depends_on:
      - zookeeper
    networks:
      - hostnet
    environment:
      BROKER_OPTS: >-
        --override broker.id=2
        --override advertised.listeners=INSIDE://:9094,OUTSIDE://localhost:9093
        --override listeners=INSIDE://:9094,OUTSIDE://:9093
        --override listener.security.protocol.map=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        --override inter.broker.listener.name=INSIDE
        --override zookeeper.connect=zookeeper:2181
        --override num.partitions=10
networks:
  hostnet:
    