version: '3'
services:
  jaeger:
    # UI http://localhost:16686
    image: jaegertracing/all-in-one:latest
    environment:
      # - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    # networks:
    #   - hostnet
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
# networks:
#   hostnet:
    